version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:5.7'
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fib-database
    restart: always

  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: redis
    ports:
      - "6379:6379"

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client-app
    container_name: client-app
    ports:
      - "4200:4200"

  server-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./server-app
    container_name: server-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fib-database?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: always

  worker-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker-app
    container_name: worker-app
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment: # Pass environment variables to the service
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: always