FROM node:alpine

WORKDIR /app

ENV NODE_OPTIONS=--openssl-legacy-provider
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./

RUN npm install
RUN npm install -g @angular/cli

COPY . .

CMD ng serve --host 0.0.0.0
